"""empty message

Revision ID: 075ebb681001
Revises: b73cd4b7fae4
Create Date: 2022-10-04 23:57:01.677268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075ebb681001'
down_revision = 'b73cd4b7fae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planeta', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('planeta', sa.Column('password', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
