"""empty message

Revision ID: bba752fc3e93
Revises: 075ebb681001
Create Date: 2022-10-05 22:47:46.383081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bba752fc3e93'
down_revision = '075ebb681001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('personaje_id', sa.Integer(), nullable=True))
    op.add_column('favorito', sa.Column('planeta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorito', 'personaje', ['personaje_id'], ['id'])
    op.create_foreign_key(None, 'favorito', 'planeta', ['planeta_id'], ['id'])
    op.drop_constraint('personaje_ibfk_1', 'personaje', type_='foreignkey')
    op.drop_column('personaje', 'favoritos_id')
    op.drop_constraint('planeta_ibfk_1', 'planeta', type_='foreignkey')
    op.drop_column('planeta', 'favoritos_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planeta', sa.Column('favoritos_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planeta_ibfk_1', 'planeta', 'favorito', ['favoritos_id'], ['id'])
    op.add_column('personaje', sa.Column('favoritos_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('personaje_ibfk_1', 'personaje', 'favorito', ['favoritos_id'], ['id'])
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_column('favorito', 'planeta_id')
    op.drop_column('favorito', 'personaje_id')
    # ### end Alembic commands ###
